#ifndef BINDUTILS_H
#define BINDUTILS_H

#define ADD_GETSET_BINDING(GETTER_NAME, SETTER_NAME, VAR, P_VAR, CLASS_NAME, VARIANT_TYPE) ClassDB::bind_method(D_METHOD(#GETTER_NAME), &CLASS_NAME::GETTER_NAME); \
ClassDB::bind_method(D_METHOD(#SETTER_NAME, #P_VAR), &CLASS_NAME::SETTER_NAME); \
ClassDB::add_property(#CLASS_NAME, PropertyInfo(Variant::VARIANT_TYPE, #VAR), #SETTER_NAME, #GETTER_NAME); \

#define ADD_METHOD_BINDING(METHOD_NAME, CLASS_NAME) ClassDB::bind_method(D_METHOD(#METHOD_NAME), &CLASS_NAME::METHOD_NAME); \

#endif